export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";
export const ADD_USER = "ADD_USER";
export const ADD_USER_FAILED = "ADD_USER_FAILED";

export const GET_ALL_DOCUMENTS = "GET_ALL_DOCUMENTS";
export const GET_ALL_SUCCESS = "GET_ALL_SUCCESS";
export const GET_ALL_FAILED = "GET_ALL_FAILED";

export const GET_DOCUMENT = "GET_ALL_FAILED";

export const UPLOAD_DOCUMENT = "UPLOAD_DOCUMENT";
export const UPLOAD_DOCUMENT_SUCCESS = "UPLOAD_DOCUMENT_SUCCESS";
export const UPLOAD_DOCUMENT_FAILED = "UPLOAD_DOCUMENT_FAILED";

export const GET_REQUESTED_DOCUMENT = "GET_REQUESTED_DOCUMENT";
export const GET_REQUESTED_DOCUMENT_SUCCESS = "GET_REQUESTED_DOCUMENT_SUCCESS";
export const GET_REQUESTED_DOCUMENT_FAILED = "GET_REQUESTED_DOCUMENT_FAILED";

export const ADD_REQUESTED_DOCUMENT = "ADD_REQUESTED_DOCUMENT";
export const ADD_REQUESTED_DOCUMENT_SUCCESS = "ADD_REQUESTED_DOCUMENT_SUCCESS";
export const ADD_REQUESTED_DOCUMENT_FAILED = "ADD_REQUESTED_DOCUMENT_FAILED";

export const VIEW_FILE = "VIEW_FILE";
export const VIEW_FILE_SUCCESS = "VIEW_FILE_SUCCESS";
export const VIEW_FILE_FILED = "VIEW_FILE_FILED";

export const DOWNLOAD_ALL = "DOWNLOAD_ALL";
export const DOWNLOAD_ALL_SUCCESS = "DOWNLOAD_ALL_SUCCESS";
export const DOWNLOAD_ALL_FILED = "DOWNLOAD_ALL_FILED";
