export const COPY = {
  ADHAR: "Adhar card",
  PAN: "Pan card",
  SSC_MARKSHEET: "SSC marksheet",
  HSC_MARKSHEET: "HSC marksheet",
  GRADUATION: "Graduation",
  EXPERIANCE: "Experiance letter / Relieving letter",
  PHOTO: "Photo",
  ACTION_REQUIRED: "Action Required *",
  ACTION_ITEMS:
    "Here are your actions to complete by at least one week before your first day.",
  LOGIN_HEADING_LABEL: "Login to your account",
  LOG_IN: "Login",
  SIGN_IN: "SignIn",
  ALT_TEXT_LOGO: "Clairvoyant by an EXL",
  EMAIL_REQUIRED: "Email Required",
  ENTER_VALID_EMAIL: "Enter Valid Email",
  PASSWORD_REQUIRED: "Password Required",
  EMAIL: "Email",
  PASSWORD: "Password",
  FORGOT_PASSWORD: "Forgot Password",
  BACK: "Back",
  SEND: "Send",
  WELCOME: "Welcome",
  UPLOAD_FILES: "Upload Files",
  UPLOADED_FILE_PLACEHOLDER: "{0} files selected",
  UPLOAD: "Upload",
  VIEW_FILE: "View File",
  PROFILE: "Profile",
  LOGOUT: "Logout",
  ALL_RIGHTS_RESERVED: "All Rights Reserved",
  CLV: "Clairvoyant by an EXL",
  VERSION: 'Version 1.0',
  REGISTER_CANDIDATE:'Register Candidate',
  REGISTER:'Register',
  SUBMIT: "Submit"
};
